# Generated by Django 4.2.4 on 2023-08-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvilableSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XXS', models.IntegerField(blank=True, default=0)),
                ('XS', models.IntegerField(blank=True, default=0)),
                ('S', models.IntegerField(blank=True, default=0)),
                ('M', models.IntegerField(blank=True, default=0)),
                ('L', models.IntegerField(blank=True, default=0)),
                ('XL', models.IntegerField(blank=True, default=0)),
                ('xxL', models.IntegerField(blank=True, default=0)),
                ('xxxL', models.IntegerField(blank=True, default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
    ]
