# Generated by Django 4.2.4 on 2023-08-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_l_product_m_product_s_product_xl_product_xs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
    ]
