# Generated by Django 4.2.4 on 2023-08-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='xxL',
            new_name='XXL',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='xxxL',
            new_name='XXXL',
        ),
    ]
