# Generated by Django 4.2.4 on 2023-08-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
