# Generated by Django 4.2.4 on 2023-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagegoogle',
            field=models.URLField(blank=True, default='https://www.example.com', null=True),
        ),
    ]
