# Generated by Django 4.2.4 on 2023-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_imagegoogle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=30, null=True, unique=True),
        ),
    ]
