# Generated by Django 4.2.4 on 2023-09-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_signature',
        ),
    ]
