# Generated by Django 4.2.4 on 2023-08-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.shippingaddress'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
