# Generated by Django 4.2.4 on 2023-08-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_customuser'),
    ]

    operations = [
    ]
