# Generated by Django 4.2.4 on 2023-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_customuser_isverified_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
